language: python
python:
  - '2.7'
sudo: false
cache:
  directories:
    - "~/.platformio"
install:
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio lib install
script:
  - platformio run
before_deploy:
  - ./.prepare_release
